#For privacy reasons please change all data with your personal one known only by you!
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS:?}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASS:?}"]
    ports:
      - "6379:6379"
    environment:
      REDIS_USERNAME: ${REDIS_USER:-default}
      REDIS_PASSWORD: ${REDIS_PASS:?}
    volumes:
      - redis_data:/data

  producer:
    build: ./producer
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DEV_MODE=false
      - EMAIL_TRPC_URL=none
      - MONGO_CONNECTION_STRING=mongodb://${MONGO_ROOT_USER:-root}:${MONGO_ROOT_PASS:?}@mongo:27017/Litlyx?authSource=admin
      - STREAM_NAME=LITLYX_STREAM
      - REDIS_URL=redis://redis:6379
      - REDIS_USERNAME=${REDIS_USER:-default}
      - REDIS_PASSWORD=${REDIS_PASS:?}
    depends_on:
      - mongo
      - redis

  consumer:
    build: ./consumer
    environment:
      - DEV_MODE=false
      - EMAIL_TRPC_URL=none
      - EMAIL_SECRET=none
      - MONGO_CONNECTION_STRING=mongodb://${MONGO_ROOT_USER:-root}:${MONGO_ROOT_PASS:?}@mongo:27017/Litlyx?authSource=admin
      - STREAM_NAME=LITLYX_STREAM
      - REDIS_URL=redis://redis:6379
      - REDIS_USERNAME=${REDIS_USER:-default}
      - REDIS_PASSWORD=${REDIS_PASS:?}
      - GROUP_NAME=DATABASE
    depends_on:
      - mongo
      - redis

  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"
    environment:
      - NUXT_LICENSE_KEY=${LICENSE_KEY:-}
      - NUXT_MONGO_CONNECTION_STRING=mongodb://${MONGO_ROOT_USER:-root}:${MONGO_ROOT_PASS:?}@mongo:27017/Litlyx?authSource=admin
      - NUXT_REDIS_URL=redis://redis:6379
      - NUXT_REDIS_USERNAME=${REDIS_USER:-default}
      - NUXT_REDIS_PASSWORD=${REDIS_PASS:?}
      - NUXT_BASE_URL=http://127.0.0.1:3000
      - NUXT_SESSION_PASSWORD=${JWT_SECRET:?}
      - NUXT_ADMIN_EMAIL=${ADMIN_EMAIL:?}
      - NUXT_ADMIN_PASSWORD=${ADMIN_PASS:?}
      - NUXT_PUBLIC_SELFHOSTED=true
      - NUXT_PUBLIC_AI_ENABLED=false # change to TRUE if you've provided AI keys down below
      # NUXT_AI_ORG=your_openai_org_id
      # NUXT_AI_PROJECT=your_openai_project_id
      # NUXT_AI_KEY=your_openai_api_key

    depends_on:
      - mongo
      - redis
      - producer
      - consumer

volumes:
  mongo_data:
  redis_data:
